packages:
  - "apps/*"
  - "packages/*"
nodeLinker: hoisted
peerDependencyRules:
  allowedVersions:
    "@electron/fuses": "2.1.1"
overrides:
  "@mapbox/node-pre-gyp": "2.0.3"
  "node-gyp": "12.2.0"
  "make-fetch-happen": "15.0.5"
  cacache: "20.0.4"
  tar: "7.5.13"
  "@xmldom/xmldom": "0.8.13"
  "fast-uri": "3.1.2"
  "ip-address": "10.1.1"
  "@tootallnate/once": "3.0.1"
  tmp: "0.2.4"
allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  fs-xattr: true
  get-windows: true
  koffi: true
  macos-alias: true
