packages:
  - "apps/*"
  - "packages/*"
nodeLinker: hoisted
peerDependencyRules:
  allowedVersions:
    "@electron/fuses": "2.1.2"
overrides:
  "@mapbox/node-pre-gyp": "2.0.3"
  "node-gyp": "12.2.0"
  "make-fetch-happen": "15.0.5"
  cacache: "20.0.4"
  tar: "7.5.13"
  "@xmldom/xmldom": "0.8.13"
  "fast-uri": "3.1.2"
  "ip-address": "10.1.1"
  "@tootallnate/once": "3.0.1"
  "@electron/node-gyp": "10.2.0-electron.1"
  tmp: "0.2.6"
  "brace-expansion@5.0.5": "5.0.6"
  rolldown: "1.0.1"
minimumReleaseAgeExclude:
  - "@napi-rs/wasm-runtime@1.1.5"
  - "baseline-browser-mapping@2.10.35"
  - "electron-to-chromium@1.5.371"
  - "electron@42.4.0"
  - "semver@7.8.4"
allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  fs-xattr: true
  get-windows: true
  macos-alias: true
  vue-demi: true
