import { spawn } from "child_process";
import { randomUUID } from "crypto";
import { promises as fs } from "fs";
import { tmpdir } from "os";
import path from "path";
import { DEFAULT_YTDLP_ARGS } from "./settings.js";
import { AppSettings, SubtitleCue, SubtitleLoadResult, SubtitleTrack } from "./types.js";
import { logger } from "./logger.js";

const LANGUAGE_PRIORITY = [
  "zh-Hans",
  "zh-CN",
  "zh-Hant",
  "zh-TW",
  "zh",
  "en-US",
  "en-GB",
  "en"
];

const SUBTITLE_EXTENSIONS = ["vtt", "srt"];

type BinaryResolver = () => Promise<string>;
type SettingsProvider = () => Pick<AppSettings, "ytDlpArgs">;

export class SubtitleService {
  private cache = new Map<string, SubtitleLoadResult>();
  private inflight = new Map<string, Promise<SubtitleLoadResult>>();

  constructor(
    private readonly binaryResolver: BinaryResolver = async () => "yt-dlp",
    private readonly settingsProvider: SettingsProvider = () => ({ ytDlpArgs: DEFAULT_YTDLP_ARGS })
  ) {}

  async getSubtitles(videoUrl: string): Promise<SubtitleLoadResult> {
    const cached = this.cache.get(videoUrl);
    if (cached) {
      return cached;
    }

    const inProgress = this.inflight.get(videoUrl);
    if (inProgress) {
      return inProgress;
    }

    const job = this.downloadSubtitles(videoUrl);
    this.inflight.set(videoUrl, job);

    try {
      const result = await job;
      this.cache.set(videoUrl, result);
      return result;
    } finally {
      this.inflight.delete(videoUrl);
    }
  }

  private async downloadSubtitles(videoUrl: string): Promise<SubtitleLoadResult> {
    const workingDir = await fs.mkdtemp(path.join(tmpdir(), "usp-"));
    const baseOutput = path.join(workingDir, randomUUID());
    const args = this.buildArgs(videoUrl, baseOutput);
    let binaryPath: string | null = null;

    try {
      binaryPath = await this.binaryResolver();
      logger.log("USP", `Starting yt-dlp for: ${videoUrl}`);
      
      await runCommand(binaryPath, args, workingDir);
      logger.log("USP", "yt-dlp command completed successfully");
      
      const subtitleFiles = (await fs.readdir(workingDir))
        .filter((file) => SUBTITLE_EXTENSIONS.some((ext) => file.toLowerCase().endsWith(`.${ext}`)))
        .map((file) => path.join(workingDir, file));

      if (subtitleFiles.length === 0) {
        throw new Error("未找到字幕文件，请确认该视频是否提供字幕。");
      }

      logger.log("USP", `Found ${subtitleFiles.length} subtitle file(s)`);

      const tracks: SubtitleTrack[] = [];
      for (const filePath of subtitleFiles) {
        const content = await fs.readFile(filePath, "utf-8");
        const ext = path.extname(filePath).slice(1).toLowerCase();
        const cues = parseSubtitle(content, ext);
        if (!cues.length) continue;

        const language = detectLanguage(filePath);
        tracks.push({
          id: randomUUID(),
          language,
          label: formatTrackLabel(filePath, language),
          sourceFile: path.basename(filePath),
          cues,
          isAutoGenerated: isAutoSubtitle(filePath)
        });
      }

      if (!tracks.length) {
        throw new Error("字幕文件解析失败或为空。");
      }

      logger.log("USP", `Successfully parsed ${tracks.length} subtitle track(s)`);

      return {
        tracks
      };
    } catch (error) {
      const commandLine = binaryPath ? formatCommandLine(binaryPath, args) : "";
      if (error instanceof CommandExecutionError) {
        logger.error("USP", "yt-dlp command failed", {
          command: commandLine,
          exitCode: error.info.exitCode,
          stderr: error.info.stderr,
          stdout: error.info.stdout
        });
      } else {
        logger.error("USP", "yt-dlp invocation failed", error);
      }
      const detailedMessage = formatCommandError(error, commandLine);
      throw new Error(`[yt-dlp] ${detailedMessage}`);
    } finally {
      await fs.rm(workingDir, { recursive: true, force: true });
    }
  }

  private buildArgs(videoUrl: string, baseOutput: string): string[] {
    const settings = this.settingsProvider ? this.settingsProvider() : { ytDlpArgs: DEFAULT_YTDLP_ARGS };
    const customLine = settings?.ytDlpArgs?.trim() || DEFAULT_YTDLP_ARGS;
    const customArgs = splitArgs(customLine);
    return [
      ...customArgs,
      "-o",
      baseOutput,
      videoUrl
    ];
  }
}

type CommandResult = {
  stdout: string;
  stderr: string;
};

type CommandErrorInfo = CommandResult & {
  exitCode: number | null;
  command: string;
  args: string[];
};

class CommandExecutionError extends Error {
  info: CommandErrorInfo;
  constructor(message: string, info: CommandErrorInfo) {
    super(message);
    this.name = "CommandExecutionError";
    this.info = info;
  }
}

async function runCommand(cmd: string, args: string[], cwd: string): Promise<CommandResult> {
  return new Promise<CommandResult>((resolve, reject) => {
    const child = spawn(cmd, args, { cwd });
    const info: CommandErrorInfo = {
      command: cmd,
      args,
      exitCode: null,
      stdout: "",
      stderr: ""
    };

    child.stdout?.on("data", (chunk) => {
      info.stdout += chunk.toString();
    });

    child.stderr?.on("data", (chunk) => {
      info.stderr += chunk.toString();
    });

    child.on("error", (err) => {
      const enoent = (err as NodeJS.ErrnoException).code === "ENOENT";
      const message = enoent
        ? "未找到 yt-dlp 可执行文件，请先安装 yt-dlp 并确保其在 PATH 中。"
        : err?.message || "yt-dlp 调用失败。";
      reject(new CommandExecutionError(message, info));
    });

    child.on("close", (code) => {
      if (code === 0) {
        resolve({ stdout: info.stdout, stderr: info.stderr });
      } else {
        info.exitCode = code ?? null;
        reject(
          new CommandExecutionError(
            info.stderr || `yt-dlp exited with code ${code}`,
            info
          )
        );
      }
    });
  });
}

function detectLanguage(filePath: string): string {
  const base = path.basename(filePath);
  for (const extension of SUBTITLE_EXTENSIONS) {
    const regex = new RegExp(`\\.([^.]+)\\.${extension}$`, "i");
    const match = base.match(regex);
    if (match) {
      return match[1];
    }
  }
  return "unknown";
}

function formatTrackLabel(filePath: string, language: string): string {
  const parts = [language];
  if (isAutoSubtitle(filePath)) {
    parts.push("自动");
  }
  return parts.filter(Boolean).join(" · ") || path.basename(filePath);
}

function isAutoSubtitle(filePath: string): boolean {
  return /\.auto\./i.test(filePath);
}

export function pickBestTrack(tracks: SubtitleTrack[]): SubtitleTrack {
  return (
    tracks
      .map((track) => {
        const langIndex = LANGUAGE_PRIORITY.indexOf(track.language);
        const languageWeight = langIndex === -1 ? LANGUAGE_PRIORITY.length + 1 : langIndex;
        const autoPenalty = track.isAutoGenerated ? 0.5 : 0;
        return {
          track,
          weight: languageWeight + autoPenalty
        };
      })
      .sort((a, b) => a.weight - b.weight)[0].track
  );
}

function parseSubtitle(content: string, extension: string): SubtitleCue[] {
  if (extension === "srt") {
    return parseSrt(content);
  }
  return parseVtt(content);
}

function parseVtt(content: string): SubtitleCue[] {
  const lines = content.replace(/\r/g, "").split("\n");
  const cues: SubtitleCue[] = [];
  let i = 0;

  while (i < lines.length) {
    let line = lines[i].trim();

    if (!line || line.startsWith("WEBVTT")) {
      i += 1;
      continue;
    }

    if (line.includes("-->")) {
      const [startRaw, endRaw] = line.split("-->");
      const start = parseTimestamp(startRaw.trim());
      const end = parseTimestamp(endRaw.trim());
      const textLines: string[] = [];

      i += 1;
      while (i < lines.length && lines[i].trim() !== "") {
        textLines.push(stripTags(lines[i]));
        i += 1;
      }

      const text = textLines.join("\n").trim();
      if (!Number.isNaN(start) && !Number.isNaN(end) && text) {
        cues.push({ start, end, text });
      }
      i += 1;
      continue;
    } else {
      i += 1;
    }
  }

  return cues;
}

function parseSrt(content: string): SubtitleCue[] {
  const blocks = content.replace(/\r/g, "").split(/\n\s*\n/);
  const cues: SubtitleCue[] = [];

  for (const block of blocks) {
    const lines = block.split("\n").map((line) => line.trim()).filter(Boolean);
    if (!lines.length) continue;

    let cursor = 0;
    if (/^\d+$/.test(lines[cursor])) {
      cursor += 1;
    }
    if (cursor >= lines.length) continue;

    const timingLine = lines[cursor];
    const match = timingLine.match(/(.+?)\s+-->\s+(.+)/);
    if (!match) continue;

    const start = parseTimestamp(match[1].trim());
    const end = parseTimestamp(match[2].trim());
    const text = lines.slice(cursor + 1).map(stripTags).join("\n").trim();
    if (!Number.isNaN(start) && !Number.isNaN(end) && text) {
      cues.push({ start, end, text });
    }
  }

  return cues;
}

function stripTags(input: string): string {
  return input.replace(/<\/?[^>]+>/g, "");
}

function splitArgs(input: string): string[] {
  const result: string[] = [];
  let current = "";
  let quote: string | null = null;

  for (let i = 0; i < input.length; i += 1) {
    const char = input[i];
    if (quote) {
      if (char === quote) {
        quote = null;
      } else if (char === "\\" && input[i + 1] === quote) {
        current += quote;
        i += 1;
      } else {
        current += char;
      }
      continue;
    }

    if (char === "\"" || char === "'") {
      quote = char;
      continue;
    }

    if (/\s/.test(char)) {
      if (current) {
        result.push(current);
        current = "";
      }
      continue;
    }

    current += char;
  }

  if (current) {
    result.push(current);
  }

  return result;
}

function parseTimestamp(value: string): number {
  const normalized = value.replace(/,/g, ".");
  const match = normalized.match(/(?:(\d+):)?(\d{2}):(\d{2}(?:\.\d+)?)/);
  if (!match) {
    return NaN;
  }

  const hours = match[1] ? Number(match[1]) : 0;
  const minutes = Number(match[2]);
  const seconds = Number(match[3]);
  return hours * 3600 + minutes * 60 + seconds;
}

function formatCommandLine(binary: string, args: string[]): string {
  return [binary, ...args]
    .map((part) => {
      if (/["\s]/.test(part)) {
        return `"${part.replace(/(["\\])/g, "\\$1")}"`;
      }
      return part;
    })
    .join(" ");
}

function formatCommandError(error: unknown, commandLine: string): string {
  const baseMessage =
    error && typeof error === "object" && "message" in error
      ? (error as Error).message
      : "未知错误";

  if (!(error instanceof CommandExecutionError)) {
    return commandLine ? `${baseMessage}\n命令: ${commandLine}` : baseMessage;
  }

  const output = (error.info.stderr || error.info.stdout || "").trim();
  const snippet = output ? trimLines(output, 40) : "";
  const parts = [baseMessage];
  if (commandLine) {
    parts.push(`命令: ${commandLine}`);
  }
  if (snippet) {
    parts.push(`输出:\n${snippet}`);
  }
  return parts.join("\n");
}

function trimLines(text: string, maxLines: number): string {
  const lines = text.split(/\r?\n/).filter((line) => line.trim().length);
  if (lines.length <= maxLines) {
    return lines.join("\n");
  }
  return lines.slice(-maxLines).join("\n");
}
