import { spawn } from "child_process";
import { randomUUID } from "crypto";
import { promises as fs } from "fs";
import { tmpdir } from "os";
import path from "path";
import { SubtitleCue, SubtitleLoadResult, SubtitleTrack } from "./types.js";

const LANGUAGE_PRIORITY = [
  "zh-Hans",
  "zh-CN",
  "zh-Hant",
  "zh-TW",
  "zh",
  "en-US",
  "en-GB",
  "en"
];

export class SubtitleService {
  private cache = new Map<string, SubtitleLoadResult>();
  private inflight = new Map<string, Promise<SubtitleLoadResult>>();

  async getSubtitles(videoUrl: string): Promise<SubtitleLoadResult> {
    const cached = this.cache.get(videoUrl);
    if (cached) {
      return cached;
    }

    const inProgress = this.inflight.get(videoUrl);
    if (inProgress) {
      return inProgress;
    }

    const job = this.downloadSubtitles(videoUrl);
    this.inflight.set(videoUrl, job);

    try {
      const result = await job;
      this.cache.set(videoUrl, result);
      return result;
    } finally {
      this.inflight.delete(videoUrl);
    }
  }

  private async downloadSubtitles(videoUrl: string): Promise<SubtitleLoadResult> {
    const workingDir = await fs.mkdtemp(path.join(tmpdir(), "usp-"));
    const baseOutput = path.join(workingDir, randomUUID());
    const args = [
      "--skip-download",
      "--write-auto-sub",
      "--write-sub",
      "--sub-format",
      "vtt",
      "--convert-subs",
      "vtt",
      "--sub-langs",
      "all",
      "-o",
      baseOutput,
      videoUrl
    ];

    try {
      await runCommand("yt-dlp", args, workingDir);
      const vttFiles = (await fs.readdir(workingDir))
        .filter((file) => file.endsWith(".vtt"))
        .map((file) => path.join(workingDir, file));

      if (vttFiles.length === 0) {
        throw new Error("未找到字幕文件，请确认该视频是否提供字幕。");
      }

      const tracks: SubtitleTrack[] = [];
      for (const filePath of vttFiles) {
        const content = await fs.readFile(filePath, "utf-8");
        const cues = parseVtt(content);
        if (!cues.length) continue;

        const language = detectLanguage(filePath);
        tracks.push({
          id: randomUUID(),
          language,
          label: formatTrackLabel(filePath, language),
          sourceFile: path.basename(filePath),
          cues,
          isAutoGenerated: isAutoSubtitle(filePath)
        });
      }

      if (!tracks.length) {
        throw new Error("字幕文件解析失败或为空。");
      }

      return {
        tracks
      };
    } catch (error) {
      const message =
        error && typeof error === "object" && "message" in error
          ? (error as Error).message
          : "未知错误";
      throw new Error(`[yt-dlp] ${message}`);
    } finally {
      await fs.rm(workingDir, { recursive: true, force: true });
    }
  }
}

async function runCommand(cmd: string, args: string[], cwd: string): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    const child = spawn(cmd, args, { cwd });
    let stderr = "";

    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
    });

    child.on("error", (err) => {
      if ((err as NodeJS.ErrnoException).code === "ENOENT") {
        reject(
          new Error("未找到 yt-dlp 可执行文件，请先安装 yt-dlp 并确保其在 PATH 中。")
        );
      } else {
        reject(err);
      }
    });

    child.on("close", (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(stderr || `yt-dlp exited with code ${code}`));
      }
    });
  });
}

function detectLanguage(filePath: string): string {
  const match = filePath.match(/\.([^.]+)\.vtt$/);
  return match ? match[1] : "unknown";
}

function formatTrackLabel(filePath: string, language: string): string {
  const parts = [language];
  if (isAutoSubtitle(filePath)) {
    parts.push("自动");
  }
  return parts.filter(Boolean).join(" · ") || path.basename(filePath);
}

function isAutoSubtitle(filePath: string): boolean {
  return /\.auto\./i.test(filePath);
}

export function pickBestTrack(tracks: SubtitleTrack[]): SubtitleTrack {
  return (
    tracks
      .map((track) => {
        const langIndex = LANGUAGE_PRIORITY.indexOf(track.language);
        const languageWeight = langIndex === -1 ? LANGUAGE_PRIORITY.length + 1 : langIndex;
        const autoPenalty = track.isAutoGenerated ? 0.5 : 0;
        return {
          track,
          weight: languageWeight + autoPenalty
        };
      })
      .sort((a, b) => a.weight - b.weight)[0].track
  );
}

function parseVtt(content: string): SubtitleCue[] {
  const lines = content.replace(/\r/g, "").split("\n");
  const cues: SubtitleCue[] = [];
  let i = 0;

  while (i < lines.length) {
    let line = lines[i].trim();

    if (!line || line.startsWith("WEBVTT")) {
      i += 1;
      continue;
    }

    if (line.includes("-->")) {
      const [startRaw, endRaw] = line.split("-->");
      const start = parseTimestamp(startRaw.trim());
      const end = parseTimestamp(endRaw.trim());
      const textLines: string[] = [];

      i += 1;
      while (i < lines.length && lines[i].trim() !== "") {
        textLines.push(stripTags(lines[i]));
        i += 1;
      }

      const text = textLines.join("\n").trim();
      if (!Number.isNaN(start) && !Number.isNaN(end) && text) {
        cues.push({ start, end, text });
      }
      i += 1;
      continue;
    } else {
      i += 1;
    }
  }

  return cues;
}

function stripTags(input: string): string {
  return input.replace(/<\/?[^>]+>/g, "");
}

function parseTimestamp(value: string): number {
  const match = value.match(/(?:(\d+):)?(\d{2}):(\d{2}(?:\.\d+)?)/);
  if (!match) {
    return NaN;
  }

  const hours = match[1] ? Number(match[1]) : 0;
  const minutes = Number(match[2]);
  const seconds = Number(match[3]);
  return hours * 3600 + minutes * 60 + seconds;
}
