import { spawn } from "child_process";
import { randomUUID } from "crypto";
import { promises as fs } from "fs";
import iconv from "iconv-lite";
import { tmpdir } from "os";
import path from "path";
import { DEFAULT_PROFILE_SETTINGS, DEFAULT_YTDLP_ARGS } from "./settings.js";
import { parseSubtitle } from "./subtitleParser.js";
import { ProfileSettings, SubtitleLoadResult, SubtitleTrack } from "./types.js";
import { createLogger } from "./logger.js";
import { SubtitleCacheManager } from "./subtitleCacheManager.js";

const LANGUAGE_PRIORITY = [
  "zh-Hans",
  "zh-CN",
  "zh-Hant",
  "zh-TW",
  "zh",
  "en-US",
  "en-GB",
  "en"
];

const SUBTITLE_EXTENSIONS = ["vtt", "srt"];

type BinaryResolver = () => Promise<string>;
type SettingsProvider = () => Pick<ProfileSettings, "ytDlpArgs">;

export class SubtitleService {
  private inflight = new Map<string, Promise<SubtitleLoadResult>>();
  private readonly log = createLogger("subtitle-service");

  constructor(
    private readonly binaryResolver: BinaryResolver = async () => "yt-dlp",
    private readonly settingsProvider: SettingsProvider = () => DEFAULT_PROFILE_SETTINGS,
    private readonly cacheManager?: SubtitleCacheManager
  ) {}

  async getSubtitles(videoUrl: string): Promise<SubtitleLoadResult> {
    // Check cache first
    if (this.cacheManager) {
      const cached = await this.cacheManager.get(videoUrl, "ytdlp");
      if (cached) {
        this.log.debug("Cache hit for:", videoUrl);
        return cached;
      }
    }

    const inProgress = this.inflight.get(videoUrl);
    if (inProgress) {
      return inProgress;
    }

    const job = this.downloadSubtitles(videoUrl);
    this.inflight.set(videoUrl, job);

    try {
      const result = await job;
      // Save to cache
      if (this.cacheManager) {
        await this.cacheManager.set(videoUrl, "ytdlp", result);
      }
      return result;
    } finally {
      this.inflight.delete(videoUrl);
    }
  }

  private async downloadSubtitles(videoUrl: string): Promise<SubtitleLoadResult> {
    const workingDir = await fs.mkdtemp(path.join(tmpdir(), "usp-"));
    const baseOutput = path.join(workingDir, randomUUID());
    const args = this.buildArgs(videoUrl, baseOutput);
    let binaryPath: string | null = null;

    try {
      binaryPath = await this.binaryResolver();
      this.log.info(`Starting yt-dlp for: ${videoUrl}`);
      
      await runCommand(binaryPath, args, workingDir);
      this.log.info("yt-dlp command completed successfully");
      
      const subtitleFiles = (await fs.readdir(workingDir))
        .filter((file) => SUBTITLE_EXTENSIONS.some((ext) => file.toLowerCase().endsWith(`.${ext}`)))
        .map((file) => path.join(workingDir, file));

      if (subtitleFiles.length === 0) {
        throw new Error("No subtitles were found. Please confirm if subtitles are provided for this video.");
      }

      this.log.info(`Found ${subtitleFiles.length} subtitle file(s)`);

      const tracks: SubtitleTrack[] = [];
      for (const filePath of subtitleFiles) {
        const content = await fs.readFile(filePath, "utf-8");
        const ext = path.extname(filePath).slice(1).toLowerCase();
        const cues = parseSubtitle(content, ext);
        if (!cues.length) continue;

        const language = detectLanguage(filePath);
        tracks.push({
          id: randomUUID(),
          language,
          label: formatTrackLabel(filePath, language),
          sourceFile: path.basename(filePath),
          cues,
          isAutoGenerated: isAutoSubtitle(filePath)
        });
      }

      if (!tracks.length) {
        throw new Error("Failed to parse subtitle files or files are empty.");
      }

      this.log.info(`Successfully parsed ${tracks.length} subtitle track(s)`);

      return {
        tracks
      };
    } catch (error) {
      const commandLine = binaryPath ? formatCommandLine(binaryPath, args) : "";
      if (error instanceof CommandExecutionError) {
        this.log.error("yt-dlp command failed", {
          command: commandLine,
          exitCode: error.info.exitCode,
          stderr: error.info.stderr,
          stdout: error.info.stdout
        });
      } else {
        this.log.error("yt-dlp invocation failed", error);
      }
      const detailedMessage = formatCommandError(error, commandLine);
      throw new Error(`[yt-dlp] ${detailedMessage}`);
    } finally {
      await fs.rm(workingDir, { recursive: true, force: true });
    }
  }

  private buildArgs(videoUrl: string, baseOutput: string): string[] {
    const settings = this.settingsProvider ? this.settingsProvider() : DEFAULT_PROFILE_SETTINGS;
    const customLine = settings?.ytDlpArgs?.trim() || DEFAULT_YTDLP_ARGS;
    const customArgs = splitArgs(customLine);
    return [
      ...customArgs,
      "-o",
      baseOutput,
      videoUrl
    ];
  }
}

type CommandResult = {
  stdout: string;
  stderr: string;
};

type CommandErrorInfo = CommandResult & {
  exitCode: number | null;
  command: string;
  args: string[];
};

class CommandExecutionError extends Error {
  info: CommandErrorInfo;
  constructor(message: string, info: CommandErrorInfo) {
    super(message);
    this.name = "CommandExecutionError";
    this.info = info;
  }
}

async function runCommand(cmd: string, args: string[], cwd: string): Promise<CommandResult> {
  return new Promise<CommandResult>((resolve, reject) => {
    const child = spawn(cmd, args, { cwd });
    const info: CommandErrorInfo = {
      command: cmd,
      args,
      exitCode: null,
      stdout: "",
      stderr: ""
    };

    // On Windows, yt-dlp output may be in GBK encoding
    // Try to decode with GBK first, fall back to UTF-8 if it fails
    const decodeBuffer = (chunk: Buffer): string => {
      if (process.platform === "win32") {
        try {
          return iconv.decode(chunk, "gbk");
        } catch {
          // Fall back to UTF-8 if GBK decode fails
        }
      }
      return chunk.toString("utf8");
    };

    child.stdout?.on("data", (chunk: Buffer) => {
      info.stdout += decodeBuffer(chunk);
    });

    child.stderr?.on("data", (chunk: Buffer) => {
      info.stderr += decodeBuffer(chunk);
    });

    child.on("error", (err) => {
      const enoent = (err as NodeJS.ErrnoException).code === "ENOENT";
      const message = enoent
        ? "yt-dlp executable not found. Please install yt-dlp and ensure it's in your PATH."
        : err?.message || "yt-dlp invocation failed.";
      reject(new CommandExecutionError(message, info));
    });

    child.on("close", (code) => {
      if (code === 0) {
        resolve({ stdout: info.stdout, stderr: info.stderr });
      } else {
        info.exitCode = code ?? null;
        reject(
          new CommandExecutionError(
            info.stderr || `yt-dlp exited with code ${code}`,
            info
          )
        );
      }
    });
  });
}

function detectLanguage(filePath: string): string {
  const base = path.basename(filePath);
  for (const extension of SUBTITLE_EXTENSIONS) {
    const regex = new RegExp(`\\.([^.]+)\\.${extension}$`, "i");
    const match = base.match(regex);
    if (match) {
      return match[1];
    }
  }
  return "unknown";
}

function formatTrackLabel(filePath: string, language: string): string {
  const parts = [language];
  if (isAutoSubtitle(filePath)) {
    parts.push("Auto");
  }
  return parts.filter(Boolean).join(" · ") || path.basename(filePath);
}

function isAutoSubtitle(filePath: string): boolean {
  return /\.auto\./i.test(filePath);
}

export function pickBestTrack(tracks: SubtitleTrack[]): SubtitleTrack {
  return (
    tracks
      .map((track) => {
        const langIndex = LANGUAGE_PRIORITY.indexOf(track.language);
        const languageWeight = langIndex === -1 ? LANGUAGE_PRIORITY.length + 1 : langIndex;
        const autoPenalty = track.isAutoGenerated ? 0.5 : 0;
        return {
          track,
          weight: languageWeight + autoPenalty
        };
      })
      .sort((a, b) => a.weight - b.weight)[0].track
  );
}

function splitArgs(input: string): string[] {
  const result: string[] = [];
  let current = "";
  let quote: string | null = null;

  for (let i = 0; i < input.length; i += 1) {
    const char = input[i];
    if (quote) {
      if (char === quote) {
        quote = null;
      } else if (char === "\\" && input[i + 1] === quote) {
        current += quote;
        i += 1;
      } else {
        current += char;
      }
      continue;
    }

    if (char === "\"" || char === "'") {
      quote = char;
      continue;
    }

    if (/\s/.test(char)) {
      if (current) {
        result.push(current);
        current = "";
      }
      continue;
    }

    current += char;
  }

  if (current) {
    result.push(current);
  }

  return result;
}

function formatCommandLine(binary: string, args: string[]): string {
  return [binary, ...args]
    .map((part) => {
      if (/["\s]/.test(part)) {
        return `"${part.replace(/(["\\])/g, "\\$1")}"`;
      }
      return part;
    })
    .join(" ");
}

function formatCommandError(error: unknown, commandLine: string): string {
  const baseMessage =
    error && typeof error === "object" && "message" in error
      ? (error as Error).message
      : "Unknown error";

  if (!(error instanceof CommandExecutionError)) {
    return commandLine ? `${baseMessage}\nCommand: ${commandLine}` : baseMessage;
  }

  const output = (error.info.stderr || error.info.stdout || "").trim();
  const snippet = output ? trimLines(output, 40) : "";
  const parts = [baseMessage];
  if (commandLine) {
    parts.push(`Command: ${commandLine}`);
  }
  if (snippet) {
    parts.push(`Output:\n${snippet}`);
  }
  return parts.join("\n");
}

function trimLines(text: string, maxLines: number): string {
  const lines = text.split(/\r?\n/).filter((line) => line.trim().length);
  if (lines.length <= maxLines) {
    return lines.join("\n");
  }
  return lines.slice(-maxLines).join("\n");
}
