export interface SubtitleCue {
  start: number; // milliseconds
  end: number; // milliseconds
  text: string;
}

export interface ExtensionPayload {
  pageUrl?: string;
  site?: string;
  videoSrc?: string | null;
  playbackRate?: number;
  currentTime?: number; // milliseconds
  duration?: number | null; // milliseconds
  paused?: boolean;
  title?: string;
  muted?: boolean;
  volume?: number;
}

export type ExtensionMessageType =
  | "video-context"
  | "time-update"
  | "playback-rate"
  | "video-ended"
  | "page-url-changed"
  | "loop-cleared"
  | "loop-started";

export interface ExtensionMessage {
  tabId: number;
  type: ExtensionMessageType;
  payload: ExtensionPayload;
}

export interface SubtitleTrack {
  id: string;
  language: string;
  label: string;
  sourceFile: string;
  cues: SubtitleCue[];
  isAutoGenerated: boolean;
}

export interface SubtitleLoadResult {
  tracks: SubtitleTrack[];
}

export interface PlaybackState {
  currentTime: number; // milliseconds
  playbackRate: number;
  lastUpdate: number | null; // timestamp in milliseconds
  isLooping: boolean; // whether currently in loop mode
  loopCueIndex: number | null; // index of the cue being looped
}

export interface DesktopState {
  connectionCount: number;
  activeTabId: number | null;
  pageUrl: string | null;
  videoUrl: string | null;
  title: string | null;
  site: string | null;
  activeSource: SubtitleSource | null;
  status: "idle" | "awaiting-video" | "loading-subtitles" | "ready" | "error";
  error: string | null;
  playback: PlaybackState;
  subtitleTracks: SubtitleTrack[];
  selectedPrimarySubtitleId: string | null;
  selectedSecondarySubtitleId: string | null;
  primarySubtitles: SubtitleTrack | null;
  secondarySubtitles: SubtitleTrack | null;
  appliedProfileId: string | null;
  appliedProfileName: string | null;
  appliedRuleId: string | null;
  appliedRuleName: string | null;
  appliedRulePattern: string | null;
  appliedRuleMatchType: UrlMatchType | null;
  pendingJellyfinItemId: string | null; // Used to prevent race conditions when switching between Jellyfin and extension
  jellyfin: JellyfinPanelState;
}

export type SubtitleSource = "extension" | "jellyfin";

export type VideoControlCommand =
  | { type: "seek"; time: number } // milliseconds
  | { type: "pause" }
  | { type: "play" }
  | { type: "loop"; start: number; end: number; cueIndex: number } // milliseconds, cueIndex for UI
  | { type: "stopLoop" };

export type CloseBehavior = "quit" | "tray";

export type UrlMatchType = "contains" | "exact" | "regex";

export interface GlobalSettings {
  closeBehavior: CloseBehavior;
  autoLaunch: boolean;
  toggleWindowShortcut: string;
  gameProcessBlacklist: string[];
  autoHidePanels: boolean;
}

export interface JellyfinConfig {
  id: string;
  name: string;
  serverUrl: string;
  apiKey: string;
  webSocketPath: string;
  enabled: boolean;
}

export interface JellyfinSettings {
  enabled: boolean;
  configs: JellyfinConfig[];
}

export interface SubtitleCacheSettings {
  enabled: boolean;
  path: string;
  retentionDays: number;
}

export interface ProfileSettings {
  subtitleFontFamily: string;
  subtitleFontSize: number;
  ytDlpArgs: string;
  subtitleAutoScrollTimeout: number;
  subtitleScrollPosition: number;
  primarySubtitlePriority: string[];
  secondarySubtitlePriority: string[];
}

export interface ProfileDefinition {
  id: string;
  name: string;
  description?: string | null;
  settings: ProfileSettings;
}

export interface ProfileRule {
  id: string;
  name: string;
  pattern: string;
  matchType: UrlMatchType;
  profileId: string;
  isEnabled: boolean;
}

export interface AppSettings {
  global: GlobalSettings;
  profiles: ProfileDefinition[];
  defaultProfileId: string;
  rules: ProfileRule[];
  jellyfin: JellyfinSettings;
  cache: SubtitleCacheSettings;
}

export interface JellyfinSubtitleStream {
  index: number;
  codec: string | null;
  language: string | null;
  displayTitle: string | null;
  isDefault: boolean;
  isForced: boolean;
  isText: boolean;
}

export interface JellyfinSessionSummary {
  id: string;
  serverConfigId: string;
  serverName: string;
  deviceName: string | null;
  client: string | null;
  userName: string | null;
  nowPlayingItemId: string | null;
  nowPlayingItemName: string | null;
  mediaSourceId: string | null;
  runTimeTicks: number | null;
  positionTicks: number | null;
  isPaused: boolean;
  playbackRate: number | null;
  subtitleStreams: JellyfinSubtitleStream[];
}

export interface JellyfinPanelState {
  connected: boolean;
  sessions: JellyfinSessionSummary[];
  selectedSessionId: string | null;
  lastUpdated: number | null; // timestamp in milliseconds
}

export interface JellyfinStatusPayload {
  connected: boolean;
}

export interface JellyfinSubtitlesPayload {
  sessionId: string | null;
  itemName: string | null;
  tracks: SubtitleTrack[];
}

export interface JellyfinPlaybackPayload {
  sessionId: string | null;
  itemName: string | null;
  positionMs: number | null;
  runTimeMs: number | null;
  playbackRate: number;
  isPaused: boolean;
}
