export interface SubtitleCue {
  start: number;
  end: number;
  text: string;
}

export interface ExtensionPayload {
  pageUrl?: string;
  site?: string;
  videoSrc?: string | null;
  playbackRate?: number;
  currentTime?: number;
  duration?: number | null;
  paused?: boolean;
  title?: string;
  muted?: boolean;
  volume?: number;
}

export type ExtensionMessageType =
  | "video-context"
  | "time-update"
  | "playback-rate"
  | "video-ended"
  | "page-url-changed";

export interface ExtensionMessage {
  tabId: number;
  type: ExtensionMessageType;
  payload: ExtensionPayload;
}

export interface SubtitleTrack {
  id: string;
  language: string;
  label: string;
  sourceFile: string;
  cues: SubtitleCue[];
  isAutoGenerated: boolean;
}

export interface SubtitleLoadResult {
  tracks: SubtitleTrack[];
}

export interface PlaybackState {
  currentTime: number;
  playbackRate: number;
  lastUpdate: number | null;
}

export interface DesktopState {
  connectionCount: number;
  activeTabId: number | null;
  pageUrl: string | null;
  videoUrl: string | null;
  title: string | null;
  site: string | null;
  status: "idle" | "awaiting-video" | "loading-subtitles" | "ready" | "error";
  error: string | null;
  playback: PlaybackState;
  subtitleTracks: SubtitleTrack[];
  selectedSubtitleId: string | null;
  subtitles: SubtitleTrack | null;
}

export type VideoControlCommand =
  | { type: "seek"; time: number }
  | { type: "pause" }
  | { type: "play" };

export type CloseBehavior = "quit" | "tray";

export interface AppSettings {
  closeBehavior: CloseBehavior;
  autoLaunch: boolean;
  subtitleFontFamily: string;
  subtitleFontSize: number;
  ytDlpArgs: string;
  subtitleAutoScrollTimeout: number; // Auto-scroll timeout (seconds)
}
