export interface SubtitleCue {
  start: number;
  end: number;
  text: string;
}

export interface ExtensionPayload {
  pageUrl?: string;
  site?: string;
  videoSrc?: string | null;
  playbackRate?: number;
  currentTime?: number;
  duration?: number | null;
  paused?: boolean;
  title?: string;
  muted?: boolean;
  volume?: number;
}

export type ExtensionMessageType =
  | "video-context"
  | "time-update"
  | "playback-rate"
  | "video-ended"
  | "page-url-changed";

export interface ExtensionMessage {
  tabId: number;
  type: ExtensionMessageType;
  payload: ExtensionPayload;
}

export interface SubtitleTrack {
  id: string;
  language: string;
  label: string;
  sourceFile: string;
  cues: SubtitleCue[];
  isAutoGenerated: boolean;
}

export interface SubtitleLoadResult {
  tracks: SubtitleTrack[];
}

export interface PlaybackState {
  currentTime: number;
  playbackRate: number;
  lastUpdate: number | null;
}

export interface DesktopState {
  connectionCount: number;
  activeTabId: number | null;
  pageUrl: string | null;
  videoUrl: string | null;
  title: string | null;
  site: string | null;
  status: "idle" | "awaiting-video" | "loading-subtitles" | "ready" | "error";
  error: string | null;
  playback: PlaybackState;
  subtitleTracks: SubtitleTrack[];
  selectedPrimarySubtitleId: string | null;
  selectedSecondarySubtitleId: string | null;
  primarySubtitles: SubtitleTrack | null;
  secondarySubtitles: SubtitleTrack | null;
  appliedProfileId: string | null;
  appliedProfileName: string | null;
  appliedRuleId: string | null;
  appliedRuleName: string | null;
  appliedRulePattern: string | null;
  appliedRuleMatchType: UrlMatchType | null;
}

export type VideoControlCommand =
  | { type: "seek"; time: number }
  | { type: "pause" }
  | { type: "play" };

export type CloseBehavior = "quit" | "tray";

export type UrlMatchType = "contains" | "exact" | "regex";

export interface GlobalSettings {
  closeBehavior: CloseBehavior;
  autoLaunch: boolean;
}

export interface ProfileSettings {
  subtitleFontFamily: string;
  subtitleFontSize: number;
  ytDlpArgs: string;
  subtitleAutoScrollTimeout: number;
  subtitleScrollPosition: number;
  primarySubtitlePriority: string[];
  secondarySubtitlePriority: string[];
}

export interface ProfileDefinition {
  id: string;
  name: string;
  description?: string | null;
  settings: ProfileSettings;
}

export interface ProfileRule {
  id: string;
  name: string;
  pattern: string;
  matchType: UrlMatchType;
  profileId: string;
  isEnabled: boolean;
}

export interface AppSettings {
  global: GlobalSettings;
  profiles: ProfileDefinition[];
  defaultProfileId: string;
  rules: ProfileRule[];
}
