import {
  DEFAULT_CACHE_SETTINGS,
  DEFAULT_GLOBAL_SETTINGS,
  DEFAULT_PROFILE_ID,
  DEFAULT_PROFILE_SETTINGS
} from "../../common/defaultSettings.js";

export {
  DEFAULT_CACHE_SETTINGS,
  DEFAULT_GLOBAL_SETTINGS,
  DEFAULT_PROFILE_ID,
  DEFAULT_PROFILE_SETTINGS
};

export const SUPPORTED_LANGUAGES = ["en", "zh"];
